"""Initial migration

Revision ID: 0f97f6d42c4b
Revises: 
Create Date: 2025-11-22 18:30:40.931735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f97f6d42c4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('patient', 'provider', name='userrole'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('patient_user_id', sa.String(), nullable=True),
    sa.Column('provider_user_id', sa.String(), nullable=True),
    sa.Column('appointment_time', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'rescheduled', 'checked_in', 'completed', 'cancelled', name='appointmentstatus'), nullable=False),
    sa.Column('risk_level', sa.Enum('none', 'low', 'medium', 'high', name='risklevel'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_time'), 'appointments', ['appointment_time'], unique=False)
    op.create_index(op.f('ix_appointments_patient_user_id'), 'appointments', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_appointments_provider_user_id'), 'appointments', ['provider_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_provider_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_time'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
